version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      # Set user/password for Postgres
      POSTGRES_DB: enei2020
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
